### ISSUE TITLE
Map backend response to Krakend response

### ISSUE THREAD

**Issue by jgardezi** [krakendio/krakend-lua#33]
Using Lua script, I can access and see the backend response code and body using `print(resp:statusCode())` and `print(resp:body())`. It shows me 

```
function post_proxy_decorator(resp)
  print('Hi from no-op POST-Function!')
  local responseCode = resp:statusCode()
  local responseBody = resp:body()

  print(responseCode)
  print(responseBody)
  -- resp:body('{"foo": "bar"}')
end

// response code
401  
// response body
{"error":"unauthorized","extra_info":{"reason":"jwt_verification_failed"},"http_code":401,"message":null}
```

However, I cannot forward or set this **401** response code and the body to the end user. The end user sees the following 
```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Vary: Origin
X-Krakend: Version 2.1.2
X-Krakend-Completed: false
Date: Fri, 11 Nov 2022 11:46:23 GMT
Content-Length: 2
Connection: close

{}
```

I know that in the script below, if I add `"output_encoding": "no-op"` the entire backend response will be mapped, which is not what I want. 

**Is there any way to forward or pipe the backend response code to the krakend response (end-user) without mapping the entire backend response?**

```
{
  "endpoint": "/users/me2",
  "method": "GET",
  {{ include "input_headers.tmpl" }},
  "extra_config": {
    {{ include "response_lua_proxy.tmpl" }}
  },
  "backend": [
    {
      "encoding": "no-op",
      "url_pattern": "/whoami",
      "method": "GET",
      "host": ["{{ .env.backend }}"]
    }
  ]
}
```

**Comment by jgardezi** [comment]
No response yet, on the above by anyone?

 Is there a way to remove headers from the backend when `"output_encoding": "no-op"` is used?

**Comment by kpacha** [comment]
Yes, there are several ways:

1. Use a martian modifier called `header.Blacklist` (https://github.com/google/martian/blob/master/header/header_blacklist_modifier.go)
2. Use a lua snippet accessing the response and deleting the desired header (https://www.krakend.io/docs/endpoints/lua/#response-functions-response)
3. Use a response modifier plugin (https://www.krakend.io/docs/extending/plugin-modifiers/)
